AWSTemplateFormatVersion: '2010-09-09'  # CloudFormation template version (always this for now)
Description: >
  CloudFormation template to provision two S3 buckets for the Photo Site:
  - Raw photo uploads (private, versioned)
  - Static website hosting (private, CloudFront will serve this later)

Resources:

  # -------------------------------
  # Bucket for raw photo uploads
  # -------------------------------
  PhotoUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "photo-site-raw-uploads-dev-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Project
          Value: PhotoSite
        - Key: Environment
          Value: Dev

  # -----------------------------------------
  # Bucket to host the static website content
  # -----------------------------------------
  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "photo-site-static-hosting-dev-${AWS::AccountId}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      AccessControl: Private
      Tags:
        - Key: Project
          Value: PhotoSite
        - Key: Environment
          Value: Dev

# -------------------------------------
# Outputs let you reference these values
# in CI/CD logs, other stacks, or testing
# -------------------------------------
Outputs:

  PhotoUploadBucketName:
    Description: Name of the raw upload bucket
    Value: !Ref PhotoUploadBucket

  StaticWebsiteBucketName:
    Description: Name of the static hosting bucket
    Value: !Ref StaticWebsiteBucket
